# Iron Dome Local Makefile
# This allows running the system from within the iron_dome directory

run:
	@cd .. && make run-iron-dome

help:
	@echo "Iron Dome System"
	@echo "  make run  - Run the system (redirects to root Makefile)"
